In [2]:
from sklearn.datasets import make_regression,load_diabetes
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import cross_val_score

In [3]:
x,y=load_diabetes(return_X_y=True)

In [4]:
x.shape


(442, 10)

In [6]:
y.shape

(442,)

# Using SKlearn:->

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
x_train.shape

(353, 10)

In [9]:
x_test.shape

(89, 10)

In [10]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [11]:
from sklearn.metrics import r2_score
sky_pred=lr.predict(x_test)
r2_score(y_test,sky_pred)

0.4526027629719195

In [12]:
lr.intercept_

np.float64(151.34560453985995)

In [13]:
lr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [14]:
np.mean(cross_val_score(lr,x,y,scoring='r2',cv=10))

np.float64(0.4619602420450601)

# NOW OUR WON CLass for GRADIENT DECENT:

In [78]:
import numpy as np
class GDRegressor:
    def __init__(self,lerning_rate,epochs):
        self.intercept_=None # Randomly select
        self.coff_=None #Randomly select
        self.lr=lerning_rate
        self.epochs=epochs
    def fit(self,x,y):
        self.intercept_=0
        self.coff_=np.ones(x.shape[1])
        for i in range(self.epochs):
            y_pred= np.dot(x,self.coff_)+self.intercept_
            inter_derives=-2*np.mean(y-y_pred) 
            self.intercept_=self.intercept_-(self.lr*inter_derives)
            coef_dev=-2*np.dot((y-y_pred),x)/x.shape[0]
            self.coff_=self.coff_-(self.lr*coef_dev)
        print(self.intercept_)
        print(self.coff_)
    def predict(self,x):
        return np.dot(x,self.coff_)+self.intercept_
            
    



In [91]:
gd=GDRegressor(0.5,1000)

In [92]:
gd.fit(x_test,y_test)   # this is same as the code sklearm

153.25008436127075
[ -93.92356607 -153.36310717  406.44063525  184.91357698   66.18852851
  -57.84927836 -189.37976358   78.70218465  525.15933401  137.30087405]


In [93]:
y_pred=gd.predict(x_test)

In [94]:
y_pred

array([166.77128935, 151.68691069, 170.67906875, 274.17122492,
       135.08299347, 121.66180296, 247.27788674, 222.28008907,
       121.0994897 , 133.28398639, 115.55003116, 152.39943898,
        67.52675782, 209.39262115, 113.85545019, 127.44552475,
       230.07777642, 228.37330589, 163.14049035, 199.42743574,
       215.90207155,  99.28164606,  84.82228665, 184.5916717 ,
       157.02035097, 145.96793652, 166.13458766, 153.55483335,
        64.89297785, 129.23764969, 168.19312764, 106.85682607,
       150.42412904, 178.20427613, 172.99660216, 210.53253692,
       139.11150763, 141.81167979, 158.63089245,  64.99078382,
        86.09402849, 101.25002423, 141.4752916 , 147.50570444,
       188.02472081,  73.69413648,  94.50647417, 101.02017046,
        60.65770541, 168.2788243 , 134.44812065,  85.98048959,
       100.02421927, 110.44232886, 186.76871225, 139.74264435,
       114.29819779, 186.15601207, 125.90040237,  86.38332748,
       200.48951939, 197.87097172, 137.81153394, 111.79

In [95]:
y_test

array([219.,  70., 202., 230., 111.,  84., 242., 272.,  94.,  96.,  94.,
       252.,  99., 297., 135.,  67., 295., 264., 170., 275., 310.,  64.,
       128., 232., 129., 118., 263.,  77.,  48., 107., 140., 113.,  90.,
       164., 180., 233.,  42.,  84., 172.,  63.,  48., 108., 156., 168.,
        90.,  52., 200.,  87.,  90., 258., 136., 158.,  69.,  72., 171.,
        95.,  72., 151., 168.,  60., 122.,  52., 187., 102., 214., 248.,
       181., 110., 140., 202., 101., 222., 281.,  61.,  89.,  91., 186.,
       220., 237., 233.,  68., 190.,  96.,  72., 153.,  98.,  37.,  63.,
       184.])

In [96]:
r2_score(y_test,y_pred)

0.5028284431863914