In [61]:
import pandas as  pd
import numpy as np
from sklearn.datasets import load_diabetes


In [62]:
x,y=load_diabetes(return_X_y=True)

In [63]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [64]:
x.shape


(442, 10)

In [65]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [66]:
y.shape

(442,)

# Using SKlearn:->

In [67]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [68]:
x_train.shape

(353, 10)

In [69]:
x_test.shape

(89, 10)

In [70]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [71]:
x_test

array([[ 0.04534098, -0.04464164, -0.00620595, -0.01599898,  0.1250187 ,
         0.1251981 ,  0.019187  ,  0.03430886,  0.03243232, -0.0052198 ],
       [ 0.09256398, -0.04464164,  0.03690653,  0.02187239, -0.02496016,
        -0.01665815,  0.00077881, -0.03949338, -0.02251653, -0.02178823],
       [ 0.06350368,  0.05068012, -0.00405033, -0.01255612,  0.10300346,
         0.04878988,  0.05600338, -0.00259226,  0.08449153, -0.01764613],
       [ 0.09619652, -0.04464164,  0.0519959 ,  0.07926471,  0.05484511,
         0.03657709, -0.07653559,  0.14132211,  0.09864806,  0.06105391],
       [ 0.01264814,  0.05068012, -0.02021751, -0.00222757,  0.03833367,
         0.05317395, -0.00658447,  0.03430886, -0.00514219, -0.00936191],
       [ 0.0090156 , -0.04464164, -0.02452876, -0.02632753,  0.0988756 ,
         0.0941964 ,  0.07072993, -0.00259226, -0.02139531,  0.00720652],
       [-0.00914709,  0.05068012,  0.17055523,  0.01498668,  0.03007796,
         0.03375875, -0.02131102,  0.03430886

In [72]:
y_test

array([219.,  70., 202., 230., 111.,  84., 242., 272.,  94.,  96.,  94.,
       252.,  99., 297., 135.,  67., 295., 264., 170., 275., 310.,  64.,
       128., 232., 129., 118., 263.,  77.,  48., 107., 140., 113.,  90.,
       164., 180., 233.,  42.,  84., 172.,  63.,  48., 108., 156., 168.,
        90.,  52., 200.,  87.,  90., 258., 136., 158.,  69.,  72., 171.,
        95.,  72., 151., 168.,  60., 122.,  52., 187., 102., 214., 248.,
       181., 110., 140., 202., 101., 222., 281.,  61.,  89.,  91., 186.,
       220., 237., 233.,  68., 190.,  96.,  72., 153.,  98.,  37.,  63.,
       184.])

In [73]:
y_pred=lr.predict(x_test)

In [74]:
y_pred

array([139.5475584 , 179.51720835, 134.03875572, 291.41702925,
       123.78965872,  92.1723465 , 258.23238899, 181.33732057,
        90.22411311, 108.63375858,  94.13865744, 168.43486358,
        53.5047888 , 206.63081659, 100.12925869, 130.66657085,
       219.53071499, 250.7803234 , 196.3688346 , 218.57511815,
       207.35050182,  88.48340941,  70.43285917, 188.95914235,
       154.8868162 , 159.36170122, 188.31263363, 180.39094033,
        47.99046561, 108.97453871, 174.77897633,  86.36406656,
       132.95761215, 184.53819483, 173.83220911, 190.35858492,
       124.4156176 , 119.65110656, 147.95168682,  59.05405241,
        71.62331856, 107.68284704, 165.45365458, 155.00975931,
       171.04799096,  61.45761356,  71.66672581, 114.96732206,
        51.57975523, 167.57599528, 152.52291955,  62.95568515,
       103.49741722, 109.20751489, 175.64118426, 154.60296242,
        94.41704366, 210.74209145, 120.2566205 ,  77.61585399,
       187.93203995, 206.49337474, 140.63167076, 105.59

In [75]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)


0.4526027629719195

In [76]:
lr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [77]:
lr.intercept_

np.float64(151.34560453985995)

# NOW OUR WON CLass for multiple linear regression:

In [116]:
import numpy as np

class MyLR:
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self, x_train, y_train):
        # Add bias (intercept) term
        x_train = np.insert(x_train, 0, 1, axis=1)
        # Normal equation: (X^T X)^-1 X^T y
        xtx = x_train.T.dot(x_train)
        xtx_inv = np.linalg.inv(xtx)
        xty = x_train.T.dot(y_train)
        weights = xtx_inv.dot(xty)
        self.intercept_ = weights[0]
        self.coef_ = weights[1:]
    
    def predict(self, x):
        # Add bias term
        x = np.insert(x, 0, 1, axis=1)
        weights = np.concatenate(([self.intercept_], self.coef_))
        return x.dot(weights)


In [117]:
mr=mylr()
mr.fit(x_train,y_train)

(353, 11)

In [118]:
mr.intercept_

In [119]:
mr.coef_