In [1]:
from sklearn.datasets import make_regression,load_diabetes
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import cross_val_score

In [2]:
x,y=load_diabetes(return_X_y=True)

In [3]:
x.shape


(442, 10)

In [4]:
y.shape

(442,)

# Using SKlearn:->

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [6]:
x_train.shape

(353, 10)

In [7]:
x_test.shape

(89, 10)

In [8]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [9]:
from sklearn.metrics import r2_score
sky_pred=lr.predict(x_test)
r2_score(y_test,sky_pred)

0.4526027629719195

In [10]:
lr.intercept_

np.float64(151.34560453985995)

In [11]:
lr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [12]:
np.mean(cross_val_score(lr,x,y,scoring='r2',cv=10))

np.float64(0.4619602420450601)

# NOW OUR WON CLass for stochastic GRADIENT DECENT:

In [14]:
x_train[42]

array([ 0.01628068, -0.04464164, -0.04500719, -0.05731319, -0.03459183,
       -0.05392282,  0.07441156, -0.0763945 , -0.04257085,  0.04034337])

In [39]:
import numpy as np
class SGDRegressor:
    def __init__(self,lerning_rate,epochs):
        self.intercept_=None # Randomly select
        self.coef_=None #Randomly select
        self.lr=lerning_rate
        self.epochs=epochs
    def fit(self,x,y):
        self.intercept_=0
        self.coef_=np.ones(x.shape[1])
        for i in range (self.epochs):
            for j in  range (x.shape[0]):
                idx=np.random.randint(0,x.shape[0])
                y_hat=np.dot(x[idx],self.coef_)+self.intercept_
                intercept_der=-2*(y[idx]-y_hat)
                self.intercept_=self.intercept_-(self.lr*intercept_der)
                coef_der=-2* np.dot(y[idx]-y_hat,x[idx])
                self.coef_=self.coef_-(self.lr * coef_der)
        print(self.intercept_)
        print(self.coef_)
    def predict(self,x):
        return np.dot(x,self.coef_)+self.intercept_
            
    



In [46]:
sd=SGDRegressor(0.05,100)

In [47]:
sd.fit(x_test,y_test)   # this is same as the code sklearm

177.4112891329337
[ -93.63425657 -128.81936007  380.03467732  183.91534188   63.52651544
  -53.68741678 -204.72508454   96.24557369  528.85695696  133.75077993]


In [48]:
y_pred=sd.predict(x_test)

In [49]:
y_pred

array([190.66395565, 173.06924519, 195.62106913, 299.62043939,
       161.86423799, 144.29720763, 269.16166634, 247.17914401,
       148.99217691, 157.93807257, 138.29766854, 178.16153019,
        90.00219179, 235.58544063, 139.47616187, 151.75722428,
       254.4045924 , 253.36358267, 187.43768256, 224.19379485,
       238.47508522, 123.19711206, 106.86369787, 209.61108622,
       177.7979221 , 171.48398208, 190.40623176, 181.22837932,
        86.99493961, 155.13739292, 189.5687991 , 130.59671978,
       175.7738435 , 205.27847849, 196.1427578 , 233.59686926,
       165.58973719, 168.70660586, 185.79017919,  87.80865627,
       108.82297955, 125.14557822, 168.55149241, 176.03440136,
       211.55149116,  95.49096712, 117.36651133, 121.93313255,
        84.25974345, 191.33571435, 154.17557268, 110.11503667,
       127.32557002, 132.93314478, 215.55607822, 160.03689773,
       137.88487905, 210.65071433, 148.3278309 , 107.1372305 ,
       224.54482291, 220.61209111, 160.5296731 , 136.38

In [50]:
y_test

array([219.,  70., 202., 230., 111.,  84., 242., 272.,  94.,  96.,  94.,
       252.,  99., 297., 135.,  67., 295., 264., 170., 275., 310.,  64.,
       128., 232., 129., 118., 263.,  77.,  48., 107., 140., 113.,  90.,
       164., 180., 233.,  42.,  84., 172.,  63.,  48., 108., 156., 168.,
        90.,  52., 200.,  87.,  90., 258., 136., 158.,  69.,  72., 171.,
        95.,  72., 151., 168.,  60., 122.,  52., 187., 102., 214., 248.,
       181., 110., 140., 202., 101., 222., 281.,  61.,  89.,  91., 186.,
       220., 237., 233.,  68., 190.,  96.,  72., 153.,  98.,  37.,  63.,
       184.])

In [51]:
r2_score(y_test,y_pred)

0.3883777145677396